# =========================
# Basic Site Settings
# =========================
title: "Andualem Welabo Tulu"
description: "PhD Candidate at University of Trento, Italy."
url: "https://andualemw1.github.io"
baseurl: ""

# =========================
# Author / Sidebar Info
# =========================
# This data is used by the sidebar.html file
author:
  name: "Andualem Welabo Tulu"
  bio: "PhD Candidate in Computer Vision"
  email: "andualemwelabo.tulu@unitn.it"
  github: "https://github.com/andualemw1"
  linkedin: "https://www.linkedin.com/in/andualem-tulu-105a7213b/"
  orcid: "https://orcid.org/0009-0002-6586-6414"
  googlescholar: "https://scholar.google.ca/citations?user=3IPS_swAAAAJ&hl=en"

# =========================
# Collections
# =========================
# Tells Jekyll to read your _publications and _talks folders
collections:
  publications:
    output: true
  talks:
    output: true

# =========================
# Markdown and Plugins
# =========================
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# THEME SETTING (DISABLED TO USE YOUR CUSTOM LAYOUT)
# theme: minima

